### ISSUE TITLE
[Question] What happens if `expo-router` is installed?

### ISSUE THREAD

**Issue by matallui** [react-native-tvos/config-tv#16]
I have this Expo app that I intend to release for Android TV. I've followed all of the steps but when I try to submit to the store I'm still getting the following error:

> APKs or Android App Bundles in this track must require the following features:android.software.leanback.

The only thing I can think of is that I'm still using `expo-router`, but when I sideload the app onto a TV it all works fine (my routing is very simple, just a couple of routes). Any ideas on how to fix this?

Also, is it possible to leave `expo-router` in the app (since it works) and still deploy to Android TV?

**Comment by matallui** [comment]
Actually, it looks like this config plugin always sets `android.software.leadback` required to `false` and, for my use-case, I want the app to only be available on the Android TV store. 

From the Android docs:
> Declare that your app is for built for Android TV by declaring the android.software.leanback feature.
> If your app runs on both mobile and TV, set the required attribute value to false. If you set the required attribute value to true, Google Play will only make your app available on Android TV OS.

**Comment by douglowder** [comment]
@matallui the `android.software.leanback` issue will be tracked in #17 . And yes, for Android TV, it should be ok to have `expo-router` included, although I have not tested it and it is not yet supported.
