### ISSUE TITLE
Invalid tag name "^50.0.0.alpha.5" of package "expo@^50.0.0.alpha.5"

### ISSUE THREAD

**Issue by jb-5murf** [react-native-tvos/config-tv#2]
When I build dev client, it ends with error: "Invalid tag name "^50.0.0.alpha.5" of package "expo@^50.0.0.alpha.5": Tags may not have any characters that encodeURIComponent encodes." Shouldn't the version be "^50.0.0-alpha.5"?

**Comment by douglowder** [comment]
@jb-5murf I'll have a look, thanks for catching this!

Dev client will not work on Apple TV -- it may work on Android TV, but I have not tested it.
