### ISSUE TITLE
Support Banner for Android

### ISSUE THREAD

**Issue by Yooooomi** [react-native-tvos/config-tv#6]
Hello! Very great job you guys are doing with the support of TV in expo!

I was wondering if there was any support to automatically generate `ic_banner`'s resource files for Android so that it renders well on Android TVs. Actual configuration gives me something like this.

<img width="1130" alt="image" src="https://github.com/react-native-tvos/config-tv/assets/17204739/5dc850de-76f9-48e0-ac01-a28897273047">

Thanks a lot for any response.

**Comment by douglowder** [comment]
@Yooooomi the plugin should definitely provide a banner image for TV.

However, I would prefer not to be responsible for "generating" it. It would be better to have the plugin look for a banner image that is sized correctly like [this one](https://github.com/react-native-tvos/react-native-tvos/blob/tvos-v0.73.0/packages/react-native/template/android/app/src/main/res/drawable/tv_banner.png), maybe at a standard location in your source like `assets/images/tv_banner.png`, or via a new plugin property that specifies the path. If it sees that the file exists, it would create the right markup in `AndroidManifest.xml`, and copy that image to the right place in the Android resources folder.

What do you think of that approach?

**Comment by Yooooomi** [comment]
Hello, thanks for the answer. Indicating it as a plugin parameter would be great indeed as it would allow having all app icons referenced in the same file.

I think the approach is fine. What about all the different sizes for android? Maybe you could reuse what expo is already doing to resize it.
